---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint

platforms:
  - name: tomcat
    groups:
      - tomcat
    image: idealista/java-role:latest
    privileged: True
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: change-log-path
verifier:
  name: goss
  lint:
    name: flake8
