---
- name: Converge
  hosts: tomcat
  pre_tasks:
    - name: Tomcat | Installing required dependencies
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
  roles:
    - java
    - tomcat-role
