---
- name: This sets up an httpd webserver
  hosts: web
  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=present
  - name: start the httpd service
    service: name=httpd state=started
  - name: example copying file with owner and permissions
    copy:
      src: /tmp/test.sh
      dest: /tmp/test.sh
      mode: 755
  - script: /tmp/test.sh
