- hosts: web
  tasks:
  - name: Ansible Basic Variable Example
    yum:
      name: "{{ packagename }}"
      state: "{{ packagestate }}"
  - name: start service
    service:
      name: httpd
      state: started
