---
  - name: Install httpd
    yum:
      name: "{{ packagename }}"
      state: "{{ packagestate }}"
    when: ansible_os_family == "RedHat"
  - name: start service
    service:
      name: "{{ servicename }}"
      state: "{{ servicestate }}"
  - name: Copy Site Files
    template: src=templates/index.j2 dest=/var/www/html/index.html
  - name: Copy config files
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
  - name: restart
    service:
      name: "{{ servicename }}"
      state: restarted
